# Generated by Django 5.1 on 2024-09-02 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.CharField(editable=False, max_length=200, verbose_name='Slug')),
                ('tags', models.CharField(max_length=200, null=True, verbose_name='Tags')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('upvotes', models.IntegerField(default=0, verbose_name='Upvotes')),
                ('share', models.IntegerField(default=0, verbose_name='Shares')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='postAuthor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
