# Generated by Django 5.1 on 2024-09-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=400, unique=True, verbose_name='Slug'),
        ),
    ]
